FROM node:16
ADD https://github.com/gothinkster/angular-realworld-example-app.git /angular-realworld-example-ap
RUN npm install -g @angular/cli && \
    npm install && \
    npm install 
CMD [ "ng serve" ]

