---
version: "3.9"
networks:
  myown_bridge:
    driver: bridge
    ipam: 
      driver: default
      config: 
        - subnet: 10.10.10.0/24
services:
  my-nginx:
    image: nginx:1.23
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: host
    networks:
      - myown_bridge
  my-sql:
    image: mysql:5.6
    ports: 
      - target: 3306
        published: 8081
        protocol: tcp
        mode: host
    networks:
      - myown_bridge
    environment:
      - MYSQL_ROOT_PASSWORD=password 
      - MYSQL_DATABASE=test
      - MYSQL_USER=directdevops
      - MYSQL_PASSWORD=directdevops
    
